//
//  ShowDetailsInteractor.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailsBusinessLogic {
    func fetchDetail()
}

protocol ShowDetailsDataStore {
    var event: Event? { get set }
}

class ShowDetailsInteractor: ShowDetailsDataStore {
    var presenter: ShowDetailsPresentationLogic?
    var eventAPI: EventAPI?
    var event: Event?

}

extension ShowDetailsInteractor: ShowDetailsBusinessLogic {
    func fetchDetail() {
        eventAPI = EventAPI()
        eventAPI?.fetch(source: event!) { [weak self] (result: Result<Event, Error>) in

            self?.presenter?.presentDetail(result)
        }
    }
}
