//
//  ShowDetailsRouter.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailsRoutingLogic {
    func sharing()
    func checkIn()
}

protocol ShowDetailsDataPassing {
    var dataStore: ShowDetailsDataStore? { get }
}

class ShowDetailsRouter: ShowDetailsDataPassing {
    weak var viewController: ShowDetailsViewController?
    var dataStore: ShowDetailsDataStore?
}

extension ShowDetailsRouter: ShowDetailsRoutingLogic {

    func sharing() {
        let sharingVC = SharingController(viewController: viewController)
        viewController?.present(sharingVC.activityVC, animated: true)

    }

    func checkIn() {
        let userController = viewController!.userController
        viewController!.present(userController.alert, animated: true, completion: nil)
    }

}
