//
//  ShowEventsInteractor.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowEventsBusinessLogic {
    func fetchEvents()
}

protocol ShowEventsDataStore {
    var event: Event? { get set }
}

class ShowEventsInteractor: ShowEventsDataStore {

    var presenter: ShowEventsPresentationLogic?
    var eventAPI: EventAPI?
    var event: Event?

}

extension ShowEventsInteractor: ShowEventsBusinessLogic {

    // poderia ser usado um worker no lugar de chamar a API
    // pelo tamanho da classe decidi simplificar neste ponto
    func fetchEvents() {
        eventAPI = EventAPI()
        eventAPI?.fetch { [weak self] (result: Result<[Event], Error>) in

            self?.presenter?.displayEvents(result: result)
        }
    }
}

