//
//  ShowEventsInteractor.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowEventsBusinessLogic {
    func fetchEvents()
}

protocol ShowEventsDataStore {
    var event: Event? { get set }
}

class ShowEventsInteractor: ShowEventsDataStore {

    var presenter: ShowEventsPresentationLogic?
    var eventAPI: EventAPIProtocol?
    var event: Event?

}

extension ShowEventsInteractor: ShowEventsBusinessLogic {

    // poderia ser usado um worker no lugar de chamar a API
    // pelo tamanho da classe decidi simplificar neste ponto
    func fetchEvents() {
        eventAPI = EventAPI()
        eventAPI?.fetch { [weak self] (result: Result<[Event], Error>) in

            switch result {
            case .success(let evt):
                self?.presenter?.displayEvents(result: .success(evt))

            case .error(let error):
                print(error)
                let alert = AlertAction(buttonTitle: "OK", handler: nil)
                let buttonAlert
                    = SingleButtonAlert(title: "Erro Na Busca dos Dados",
                                        message: "Tente novamente mais tarde",
                                        action: alert)
                self?.presenter?.displayEvents(result: .error(buttonAlert))
            }
        }
    }
}
