//
//  ShowDetailsViewController.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailsDisplayLogic: class {
    func displayDetail(viewModel: DetailViewModel)
}

class ShowDetailsViewController: UIViewController {

    var interactor: ShowDetailsBusinessLogic?

    var router: (ShowDetailsRoutingLogic & ShowDetailsDataPassing)?

    // MARK: View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        interactor?.fetchDetail()
    }

    @IBOutlet weak var titleLabel: UILabel!

    func checkin() {
    }

    func share() {
    }

}

extension ShowDetailsViewController: ShowDetailsDisplayLogic {
    func displayDetail(viewModel: DetailViewModel) {
        titleLabel.text = viewModel.title
    }
}
