//
//  ShowEventsPresenter.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxCocoa

protocol ShowEventsPresentationLogic {
    func displayEvents(result: Result<[Event], Error>)
}

class ShowEventsPresenter {

    weak var viewController: ShowEventsDisplayLogic? {
        didSet {
            viewController?.title = "Events List"
        }
    }
    
}

extension ShowEventsPresenter: ShowEventsPresentationLogic {

    func displayEvents(result: Result<[Event], Error>) {
        switch result {
        case .success(let evts):
            viewController?.viewModel.cells.accept(evts)
        case .error(_):
            break
        }
    }

}

