//
//  ShowEventsRouter.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowEventsRoutingLogic {
    func routeToDetail(_ viewModel: EventCellViewModel)
}

protocol ShowEventsDataPassing {
    var dataStore: ShowEventsDataStore? { get }
}

class ShowEventsRouter: ShowEventsDataPassing {
    weak var viewController: ShowEventsViewController?
    var dataStore: ShowEventsDataStore?

    // MARK: Navigation

    func navigateToDetails(source: ShowEventsViewController, destination: ShowDetailsViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data

    func passDataToDetail(source: ShowEventsDataStore, destination: inout ShowDetailsDataStore) {
        destination.event = source.event
    }
}

extension ShowEventsRouter: ShowEventsRoutingLogic {

    // MARK: Routing

    func routeToDetail(_ viewModel: EventCellViewModel) {
        dataStore?.event = viewModel.eventItem
        let detailsConf = ShowDetailsConfigurator()
        var destinationDS = detailsConf.viewController.router!.dataStore!
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        navigateToDetails(source: viewController!, destination: detailsConf.viewController)
    }
    
}

