//
//  ShowEventsInteractor.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowEventsBusinessLogic
{
  func doSomething(request: ShowEvents.Something.Request)
}

protocol ShowEventsDataStore
{
  //var name: String { get set }
}

class ShowEventsInteractor: ShowEventsBusinessLogic, ShowEventsDataStore
{
  var presenter: ShowEventsPresentationLogic?
  var worker: ShowEventsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowEvents.Something.Request)
  {
    worker = ShowEventsWorker()
    worker?.doSomeWork()
    
    let response = ShowEvents.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
