//
//  ShowEventsRouter.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowEventsRoutingLogic {
    func routeToDetail(_ viewModel: EventCellViewModel)
}

protocol ShowEventsDataPassing {
    var dataStore: ShowEventsDataStore? { get }
}

class ShowEventsRouter: ShowEventsDataPassing {
    weak var viewController: ShowEventsViewController?
    var dataStore: ShowEventsDataStore?

    // MARK: Routing

    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    //func navigateToSomewhere(source: ShowEventsViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    //func passDataToSomewhere(source: ShowEventsDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}

extension ShowEventsRouter: ShowEventsRoutingLogic {
    func routeToDetail(_ viewModel: EventCellViewModel) {
        
    }
}

