//
//  ShowDetailsViewController.swift
//  VSEventsProject
//
//  Created by Virgilius Santos on 16/11/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxCocoa
import RxAlamofire
import RxMapKit
import AlamofireImage
import MapKit

protocol ShowDetailsDisplayLogic: class {
    var viewModel: DetailViewModel { get }
}

class ShowDetailsViewController: UIViewController, ShowDetailsDisplayLogic, SingleButtonDialogPresenter {

    var interactor: ShowDetailsBusinessLogic?

    var router: ShowDetailsRoutingLogic?

    var viewModel = DetailViewModel()

    var disposeBag = DisposeBag()

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        bindViewModel()
        setupCollectionView()
        setupButtons()
//        setupUserController()
        interactor?.fetchDetail()
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        eventPoster.af_cancelImageRequest()
    }

    @IBOutlet weak var titleLabel: UILabel!

    @IBOutlet weak var eventPoster: UIImageView!

    @IBOutlet weak var dateLabel: UILabel!

    @IBOutlet weak var priceLabel: UILabel!

    @IBOutlet weak var descriptionTextView: UITextView!

    @IBOutlet weak var participantsCollectionView: UICollectionView!

    @IBOutlet weak var checkInButton: UIButton!

    @IBOutlet weak var shareButton: UIButton!

    @IBOutlet weak var mapView: MKMapView!

    func bindViewModel() {
        viewModel
            .eventDetail
            .map(\.title)
            .bind(to: titleLabel.rx.text)
            .disposed(by: disposeBag)

        viewModel
            .event
            .map(\.imageUrl)
            .bind(to: eventPoster.imageLoader)
            .disposed(by: disposeBag)

        viewModel
            .eventDetail
            .map(\.priceValue)
            .bind(to: priceLabel.rx.text)
            .disposed(by: disposeBag)

        viewModel
            .eventDetail
            .map(\.description)
            .bind(to: descriptionTextView.rx.text)
            .disposed(by: disposeBag)

        viewModel
            .eventDetail
            .map(\.dateString)
            .bind(to: dateLabel.rx.text)
            .disposed(by: disposeBag)

        viewModel
            .eventDetail
            .map(\.region)
            .bind(to: mapView.rx.region)
            .disposed(by: disposeBag)

        viewModel
            .eventDetail
            .map(\.annotations)
            .bind(to: mapView.rx.annotationsToShowToAnimate)
            .disposed(by: disposeBag)

        viewModel.onShowError
            .bind(to: alertMessage)
            .disposed(by: disposeBag)

    }

    func setupCollectionView() {
        let nib = UINib(nibName: PersonCollectionViewCell.cellIdentifier, bundle: nil)
        participantsCollectionView.register(nib, forCellWithReuseIdentifier: PersonCollectionViewCell.cellIdentifier)
        viewModel
            .eventCells
            .bind(to: participantsCollectionView.rx.items(
                cellIdentifier: PersonCollectionViewCell.cellIdentifier,
                cellType: PersonCollectionViewCell.self
            )) { (_, element, cell) in
                cell.viewModel = element
            }.disposed(by: disposeBag)

    }

    func setupButtons() {
        shareButton
            .rx
            .tap
            .bind { [weak self] in
                self?.router?.sharing()
            }
            .disposed(by: disposeBag)

        checkInButton
            .rx
            .tap
            .bind { [weak self] in
                self?.routeChecking()
            }
            .disposed(by: disposeBag)
    }

    func routeChecking() {
        router?.checkIn { [weak self] userInfo in
            self?.interactor?.postCheckIn(userInfo: userInfo)
        }
    }
}
