# Uncomment the next line to define a global platform for your project
  platform :ios, '12.1'
  use_frameworks!

def rx_pods
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxAlamofire','~> 4.0'
    pod 'RxDataSources'
    pod 'RxSwiftExt'
    pod 'RxMapKit'
end

def rx_pods_tests
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
end

def quick_pods_tests
    pod 'Quick', '1.3.2'
    pod 'Nimble', '7.3.1'
end

def alamofire_pods
    pod 'Alamofire',      '~> 4.7'
    pod 'AlamofireImage', '~> 3.4'
end


target 'VSEventsProject' do
    alamofire_pods
    rx_pods
end

target 'VSEventsProjectTests' do
    rx_pods_tests
    quick_pods_tests
end
