# Uncomment the next line to define a global platform for your project
  platform :ios, '12.1'
  use_frameworks!

target 'VSEventsProject' do
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
end

target 'VSEventsProjectTests' do
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
 end
