# Uncomment the next line to define a global platform for your project
  platform :ios, '12.1'
  use_frameworks!

def rx_pods
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxAlamofire','~> 4.0'
end

target 'VSEventsProject' do
  pod 'Alamofire',      '~> 4.7'
  pod 'AlamofireImage', '~> 3.4'
  rx_pods
end

target 'VSEventsProjectTests' do
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
 end
